### ISSUE TITLE
Bài 9: Bài này copy của ai khai nhanh, cho m 1 cơ hội làm lại cuộc đời

### ISSUE THREAD

**Issue by GuardianOfGods** [DaoThuHoai/BTVN_Java#3]
https://github.com/DaoThuHoai/BTVN_Java/blob/ac9aecd8073c0d790d4cb5ff5c22a37943841ef0/BTVN2/src/Bai9.java#L1-L24

**Comment by DaoThuHoai** [comment]
Cái này suy luận ra đc mà
tham khảo code C++
rồi làm code theo java mà
hicc có copy aii đâu 😑😑😞😞

**Comment by GuardianOfGods** [comment]
Không phải là suy luận, mà là cách viết if không giống các bài trước nên phải hỏi lại =))
